import Categories from "@/components/categories";
import Featured from "@/components/featured";
import Hero from "@/components/hero";
import Jobs from "@/components/jobs";
import Partners from "@/components/partners";
import Posting from "@/components/posting";
import { featuredJobs } from "@/mock-data";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <div className="pb-20">
      <Hero />
      <Partners />
      <Categories />
      <Posting />
      <Featured />
      <Jobs jobs={featuredJobs}>
        <h2 className="lg:text-5xl text-3xl md:text-4xl text-text font-[600]">
          Latest <span className="text-primary">open jobs</span>
        </h2>
      </Jobs>
    </div>
  );
};

export default HomePage;
