import {
  faBriefcase,
  faBullhorn,
  faChartPie,
  faCode,
  faDesktop,
  faMoneyBills,
  faPenRuler,
  faUsers,
} from "@fortawesome/free-solid-svg-icons";
import {
  Blinklist,
  CameraLogo,
  Canva,
  ClassPass,
  CoffeeLogo,
  Coinbase,
  Divvy,
  Dropbox,
  EmailMarketing,
  GoDaddy,
  Health,
  HealthHand,
  Kraken,
  Maze,
  Netlify,
  Nomad,
  Packer,
  Pitch,
  Pool,
  Revolut,
  Robinhood,
  Specialist1,
  Specialist2,
  Specialist3,
  Specialist4,
  Specialist5,
  Square,
  Stripe,
  Terraform,
  TransLogo,
  Triangle,
  Truebill,
  Twitter,
  Udacity,
  Webflow,
} from "./assets";
import { categoryType, companyType, jobType, perkType, specialistType } from "./interfaces";

export const featuredJobs: jobType[] = [
  {
    id: 1,
    image: EmailMarketing,
    workType: "Full Time",
    title: "Email Marketing",
    company: "Revolut",
    company_id: 7,
    location: "Madrid, Spain",
    description:
      "Revolut is looking for Email Marketing to help team looking for a job",
    tags: ["Marketing", "Design"],
  },
  {
    id: 2,
    image: Dropbox,
    workType: "Full Time",
    title: "Brand Designer",
    company: "Dropbox",
    location: "San Fransisco, US",
    description:
      "Dropbox is looking for Brand Designer to help the team looking for a job",
    tags: ["Design", "Business"],
  },
  {
    id: 3,
    image: Pitch,
    workType: "Full Time",
    title: "Email Marketing",
    company: "Pitch",
    location: "Berlin, Germany",
    description:
      "Pitch is looking for Email Marketing to help team looking for a job",
    tags: ["Marketing"],
  },
  {
    id: 4,
    image: Blinklist,
    workType: "Full Time",
    title: "Visual Designer",
    company: "Blinklist",
    location: "Granada, Spain",
    description:
      "Blinklist is looking for Email Marketing to help team looking for a job",
    tags: ["Design"],
  },
  {
    id: 5,
    image: ClassPass,
    workType: "Full Time",
    title: "Product Designer",
    company: "ClassPass",
    location: "Manchester, UK",
    description:
      "ClassPass is looking for Email Marketing to help team looking for a job",
    tags: ["Marketing", "Design"],
  },
  {
    id: 6,
    image: Canva,
    workType: "Full Time",
    title: "Lead Designer",
    company: "Canva",
    location: "Ontario, Canada",
    description:
      "Canva is looking for Email Marketing to help team looking for a job",
    tags: ["Design", "Business"],
  },
  {
    id: 7,
    image: GoDaddy,
    workType: "Full Time",
    title: "Brand Strategist",
    company: "GoDaddy",
    location: "Marseille, France",
    description:
      "GoDaddy is looking for Email Marketing to help team looking for a job",
    tags: ["Marketing"],
  },
  {
    id: 8,
    image: Twitter,
    workType: "Full Time",
    title: "Data Analyst",
    company: "Twitter",
    location: "San Diego, US",
    description:
      "Twitter is looking for Email Marketing to help team looking for a job",
    tags: ["Technology"],
  },
];

export const categories: categoryType[] = [
  {
    id: 1,
    icon: faPenRuler,
    title: "Design",
    jobs_count: 235,
  },
  {
    id: 2,
    icon: faChartPie,
    title: "Sales",
    jobs_count: 756,
  },
  {
    id: 3,
    icon: faBullhorn,
    title: "Marketing",
    jobs_count: 140,
  },
  {
    id: 4,
    icon: faMoneyBills,
    title: "Finance",
    jobs_count: 325,
  },
  {
    id: 5,
    icon: faDesktop,
    title: "Technology",
    jobs_count: 436,
  },
  {
    id: 6,
    icon: faCode,
    title: "Engineering",
    jobs_count: 542,
  },
  {
    id: 7,
    icon: faBriefcase,
    title: "Business",
    jobs_count: 211,
  },
  {
    id: 8,
    icon: faUsers,
    title: "Human Resource",
    jobs_count: 346,
  },
];

export const latest: jobType[] = [
  {
    id: 1,
    image: Nomad,
    title: 'Social Media Assistant',
    company: 'Nomad',
    location: 'Paris, France',
    tags: ['Marketing', 'Design'],
    workType: 'Full-Time',
  },
  {
    id: 2,
    image: Netlify,
    title: 'Social Media Assistant',
    company: 'Netlify',
    location: 'Paris, France',
    tags: ['Marketing', 'Design'],
    workType: 'Full-Time',
  },
  {
    id: 3,
    image: Dropbox,
    title: 'Brand Designer',
    company: 'Dropbox',
    location: 'San Fransisco, USA',
    tags: ['Marketing', 'Design'],
    workType: 'Full-Time',
  },
  {
    id: 4,
    image: Maze,
    title: 'Brand Designer',
    company: 'Maze',
    location: 'San Fransisco, USA',
    tags: ['Marketing', 'Design'],
    workType: 'Full-Time',
  },
  {
    id: 5,
    image: Terraform,
    title: 'Interactive Developer',
    company: 'Terraform',
    location: 'Hamburg, Germany',
    tags: ['Marketing', 'Design'],
    workType: 'Full-Time',
  },
  {
    id: 6,
    image: Udacity,
    title: 'Interactive Developer',
    company: 'Udacity',
    location: 'Hamburg, Germany',
    tags: ['Marketing', 'Design'],
    workType: 'Full-Time',
  },
  {
    id: 7,
    image: Packer,
    title: 'HR Manager',
    company: 'Packer',
    location: 'Lucern, Switzerland',
    tags: ['Marketing', 'Design'],
    workType: 'Full-Time',
  },
  {
    id: 8,
    image: Webflow,
    title: 'HR Manager',
    company: 'Webflow',
    location: 'Lucern, Switzerland',
    tags: ['Marketing', 'Design'],
    workType: 'Full-Time',
  },
]

export const companies: companyType[] = [
  {
    id: 1,
    title: 'Stripe',
    image: Stripe,
    description: 'Stripe is looking for Social Media Marketing expert to help manage our online networks. You will be responsible for monitoring our social media channels, creating content, finding effective ways to engage the community and incentivize others to engage on our channels.',
    tags: ['Business', 'Payment getaway'],
    vacancies_count: 7,
    company_website: 'https://stripe.com',
  },
  {
    id: 2,
    title: 'Truebill',
    image: Truebill,
    description: 'Truebill is looking for Social Media Marketing expert to help manage our online networks. You will be responsible for monitoring our social media channels, creating content, finding effective ways to engage the community and incentivize others to engage on our channels.',
    tags: ['Business'],
    vacancies_count: 7,
    company_website: 'https://truebill.com',
  },
  {
    id: 3,
    title: 'Square',
    image: Square,
    description: 'Square is looking for Social Media Marketing expert to help manage our online networks. You will be responsible for monitoring our social media channels, creating content, finding effective ways to engage the community and incentivize others to engage on our channels.',
    tags: ['Business', 'Blockchain'],
    vacancies_count: 7,
    company_website: 'https://square.com',
  },
  {
    id: 4,
    title: 'Coinbase',
    image: Coinbase,
    description: 'Coinbase is looking for Social Media Marketing expert to help manage our online networks. You will be responsible for monitoring our social media channels, creating content, finding effective ways to engage the community and incentivize others to engage on our channels.',
    tags: ['Business', 'Payment getaway'],
    vacancies_count: 7,
    company_website: 'https://coinbase.com',
  },
  {
    id: 5,
    title: 'Robinhood',
    image: Robinhood,
    description: 'Robinhood is looking for Social Media Marketing expert to help manage our online networks. You will be responsible for monitoring our social media channels, creating content, finding effective ways to engage the community and incentivize others to engage on our channels.',
    tags: ['Business'],
    vacancies_count: 7,
    company_website: 'https://robinhood.com',
  },
  {
    id: 6,
    title: 'Kraken',
    image: Kraken,
    description: 'Kraken is looking for Social Media Marketing expert to help manage our online networks. You will be responsible for monitoring our social media channels, creating content, finding effective ways to engage the community and incentivize others to engage on our channels.',
    tags: ['Business', 'Blockchain'],
    vacancies_count: 7,
    company_website: 'https://kraken.com',
  },
  {
    id: 7,
    title: 'Revolut',
    image: Revolut,
    description: 'Revolut is looking for Social Media Marketing expert to help manage our online networks. You will be responsible for monitoring our social media channels, creating content, finding effective ways to engage the community and incentivize others to engage on our channels.',
    tags: ['Business'],
    vacancies_count: 7,
    company_website: 'https://revolut.com',
  },
  {
    id: 8,
    title: 'Divvy',
    image: Divvy,
    description: 'Divvy is looking for Social Media Marketing expert to help manage our online networks. You will be responsible for monitoring our social media channels, creating content, finding effective ways to engage the community and incentivize others to engage on our channels.',
    tags: ['Business', 'Blockchain'],
    vacancies_count: 7,
    company_website: 'https://divvy.com',
  },
]

export const specialists: specialistType[] = [
  {
    id: 1,
    name: 'Célestin Gardinier',
    description: 'I’m a product designer + filmmaker currently working remotely at Twitter from beautiful Manchester, United Kingdom. I’m passionate about designing digital products that have a positive impact on the world. For 10 years, I’ve specialised in interface, experience & interaction design as well as working in user research and product strategy for product agencies, big tech companies & start-ups.',
    socials: {
      instagram: 'https://instagram.com/celestin',
      linkedin: 'https://www.linekdin.com/in/celestin',
    },
    job: 'CEO & Co-Founder',
    image: Specialist1,
  },
  {
    id: 2,
    name: 'Reynaud Colbert',
    description: 'I’m a product designer + filmmaker currently working remotely at Twitter from beautiful Manchester, United Kingdom. I’m passionate about designing digital products that have a positive impact on the world. For 10 years, I’ve specialised in interface, experience & interaction design as well as working in user research and product strategy for product agencies, big tech companies & start-ups.',
    socials: {
      instagram: 'https://instagram.com/reynaud',
      linkedin: 'https://www.linekdin.com/in/reynaud',
    },
    job: 'Co-Founder',
    image: Specialist2,
  },
  {
    id: 3,
    name: 'Arienne Lyon',
    description: 'I’m a product designer + filmmaker currently working remotely at Twitter from beautiful Manchester, United Kingdom. I’m passionate about designing digital products that have a positive impact on the world. For 10 years, I’ve specialised in interface, experience & interaction design as well as working in user research and product strategy for product agencies, big tech companies & start-ups.',
    socials: {
      instagram: 'https://instagram.com/lyon',
      linkedin: 'https://www.linekdin.com/in/lyon',
    },
    job: 'Managing Director',
    image: Specialist3,
  },
  {
    id: 4,
    name: 'Bernard Alexander',
    description: 'I’m a product designer + filmmaker currently working remotely at Twitter from beautiful Manchester, United Kingdom. I’m passionate about designing digital products that have a positive impact on the world. For 10 years, I’ve specialised in interface, experience & interaction design as well as working in user research and product strategy for product agencies, big tech companies & start-ups.',
    socials: {
      instagram: 'https://instagram.com/Bernard',
      linkedin: 'https://www.linekdin.com/in/Bernard',
    },
    job: 'Managing Director',
    image: Specialist4,
  },
  {
    id: 5,
    name: 'Christine Jhonson',
    description: 'I’m a product designer + filmmaker currently working remotely at Twitter from beautiful Manchester, United Kingdom. I’m passionate about designing digital products that have a positive impact on the world. For 10 years, I’ve specialised in interface, experience & interaction design as well as working in user research and product strategy for product agencies, big tech companies & start-ups.',
    socials: {
      instagram: 'https://instagram.com/Christine',
      linkedin: 'https://www.linekdin.com/in/Christine',
    },
    job: 'Managing Director',
    image: Specialist5,
  },
]

export const perks: perkType[] = [
  {
    id: 1,
    image: Health,
    title: 'Full Healthcare',
    description: 'We believe in thriving communities and that starts with our team being happy and healthy.',
  },
  {
    id: 2,
    image: Pool,
    title: 'Unlimited Vacation',
    description: 'We believe you should have a flexible schedule that makes space for family, wellness, and fun.',
  },
  {
    id: 3,
    image: CameraLogo,
    title: 'Skill Development',
    description: 'We believe in always learning and leveling up our skills. Whether it\'s a conference or online course.',
  },
  {
    id: 4,
    image: Triangle,
    title: 'Team Summits',
    description: 'Every 6 months we have a full team summit where we have fun, reflect, and plan for the upcoming quarter.',
  },
  {
    id: 5,
    image: CoffeeLogo,
    title: 'Remote Working',
    description: 'You know how you perform your best. Work from home, coffee shop or anywhere when you feel like it.',
  },
  {
    id: 6,
    image: TransLogo,
    title: 'Commuter Benefits',
    description: 'We\'re grateful for all the time and energy each team member puts into getting to work every day.',
  },
  {
    id: 7,
    image: HealthHand,
    title: 'We give back.',
    description: 'We anonymously match any donation our employees make (up to $/€ 600) so they can support the organizations they care about most—times two. ',
  },
]